### ISSUE TITLE
调用的时候返回403如何处理？

### ISSUE THREAD

**Issue by freeimg** [TennousuAthena/Serverless-DPlayer-PHP#3]
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested

**Comment by TennousuAthena** [comment]
请在API网关->编辑API中启用“支持CORS”

**Comment by freeimg** [comment]
谢谢！cos桶权限怎么设置呢？

**Comment by TennousuAthena** [comment]
@freeimg 私有读写即可

**Comment by freeimg** [comment]
> @freeimg 私有读写即可

3Q
